# Generated by Django 2.2.2 on 2019-07-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
