# Generated by Django 2.2.3 on 2019-07-27 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20190727_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='reciperating',
            options={'verbose_name_plural': 'Recipe Ratings'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reciperating',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
