# Generated by Django 2.2.3 on 2019-07-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20190727_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ratings',
            field=models.ManyToManyField(blank=True, to='recipes.RecipeRating'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_ratings',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
