# Generated by Django 2.2.3 on 2019-07-27 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0007_auto_20190727_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='author',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='total_ratings',
            new_name='total_rating',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ratings',
        ),
        migrations.AddField(
            model_name='recipe',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reciperating',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recipes.Recipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reciperating',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reciperating',
            unique_together={('recipe', 'created_by')},
        ),
    ]
