# Generated by Django 2.2.3 on 2019-07-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20190728_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
