# Generated by Django 2.2.3 on 2019-08-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20190801_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='average_rating',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
